### ISSUE TITLE
problems when run train.py

### ISSUE THREAD

**Issue by user23604** [Daraan/CropAndWeedDetection#5]
imported lightning and albumentations. Importing model framework...
Frameworks
Seed set to 4222
INFO:pytorch_accelerated:Setting random seeds
Namespace(settings='./settings.json', ckpt_path=None, no_log=False, test_only=False, logdir='./lightning_logs', logname=None)
{'dataset': {'accumulate_batch_size': 1,
             'batch_size': 6,
             'eval_batch_scale': 10,
             'image_size': [1280, 1280],
             'name': 'CropsOrWeed9',
             'normalize_images': False,
             'num_workers': 8,
             'seed': 4222,
             'stack2_images': True,
             'use_extra_class': 0},
 'loss': {'box_loss_weight': 0.05,
          'cls_loss_weight': 0.5,
          'obj_loss_weight': 1.0,
          'ota_loss': True},
 'lr_onecycle': {'base_momentum': 0.8,
                 'div_factor': 20.0,
                 'final_div_factor': 10000.0,
                 'max_momentum': 0.937,
                 'pct_start': 0.4},
 'lr_scheduler': {'milestone_multiplier': 0.1,
                  'milestones': [40, 50],
                  'warmup_epochs': 1,
                  'warmup_multiplier': 0.2},
 'mAP': {'iou_threshold': 0.7,
         'max_detections': 150,
         'min_confidence': 0.02,
         'nms_threshold': 0.02},
 'model': {'freeze': False,
           'load_anchors': True,
           'name': 'yolov7-e6',
           'pretrained': True,
           'weight_dataset': 'Fine24',
           'weight_path': False},
 'optimizer': {'learning_rate': 0.05,
               'lr_scheduler': 'OneCycleLR',
               'name': 'SGD',
               'weight_decay': 0.0005},
 'trainer': {'accumulate_grad_batches': 2,
             'check_val_every_n_epoch': 2,
             'ckpt_path': False,
             'deepspeed_config': {'train_batch_size': 12,
                                  'train_micro_batch_size_per_gpu': 6,
                                  'zero_allow_untested_optimizer': True,
                                  'zero_force_ds_cpu_optimizer': False,
                                  'zero_optimization': {'allgather_bucket_size': 500000000.0,
                                                        'offload_optimizer': {'device': 'cpu',
                                                                              'pin_memory': True},
                                                        'reduce_bucket_size': 500000000.0,
                                                        'stage': 2}},
             'disable_val_sanity_checks': True,
             'max_epochs': 36,
             'precision': 16,
             'strategy': 'auto',
             'val_check_interval': False}}
Using Deepseed True batch size 6

C:\Users\23604\anaconda3\envs\py200_clone\lib\site-packages\lightning_fabric\connector.py:571: `precision=16` is supported for historical reasons but its usage is discouraged. Please set your precision to 16-mixed instead!
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

...Data Module initialized
Traceback (most recent call last):
  File "D:\gitjingxiang\CropAndWeedDetection\train.py", line 382, in <module>
    train()
  File "D:\gitjingxiang\CropAndWeedDetection\train.py", line 354, in train
    pl_model = make_model(settings)
  File "D:\gitjingxiang\CropAndWeedDetection\train.py", line 207, in make_model
    pl_model = YOLO_PL(settings)
  File "D:\gitjingxiang\CropAndWeedDetection\model.py", line 663, in __init__
    self.model = create_yolov7_model(settings["model"]["name"], 
  File "C:\Users\23604\anaconda3\envs\py200_clone\lib\site-packages\pytorch_accelerated\utils.py", line 68, in wrapper_func
    result = func(*args, **kwargs)
  File "D:\gitjingxiang\CropAndWeedDetection\./Yolov7-training\yolov7\models\model_factory.py", line 40, in create_yolov7_model
    model = Yolov7Model(model_config=config)
  File "D:\gitjingxiang\CropAndWeedDetection\./Yolov7-training\yolov7\models\yolo.py", line 24, in __init__
    self.model, self.save_output_layer_idxs = create_model_from_config(
  File "D:\gitjingxiang\CropAndWeedDetection\./Yolov7-training\yolov7\models\config_builder.py", line 86, in create_model_from_config
    m_ = _create_module(module_, module_args, num_repeats, attach_idx, from_idx)
  File "D:\gitjingxiang\CropAndWeedDetection\./Yolov7-training\yolov7\models\config_builder.py", line 104, in _create_module
    else module_(*module_args)
TypeError: __init__() takes from 1 to 5 positional arguments but 6 were given

The process has ended and the exit code is 1

**Comment by Daraan** [comment]
Assure that the correct commit of Yolov7-training is checked out. The problem is that they in the next commit add an additional parameter to the model options. I think that should be the root of the problem.

I added a small change that lets you run:
```
$ git submodule status
 77eebd89cfa07ed99442323df4dd06876afe181a Yolov7-training (0.1.0-13-g77eebd8)
...
```

Can your verify that you have the same HEAD, you can try to checkout with:

```
$ git submodule update -f
Submodule path 'Yolov7-training': checked out '77eebd89cfa07ed99442323df4dd06876afe181a'
...
```

If you see another commit try to set your head with a different option.

---

If you need a later from Yolov7 other modifications need to be done elsewhere.
